import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <link
                href="https://fonts.googleapis.com/css2?family=Figtree:wght@400;700&display=swap"
                rel="stylesheet"
            />
        </head>
        <body
            style={{ fontFamily: "'Figtree', sans-serif" }} // Apply Figtree as the default font
        >
        {children}
        </body>
        </html>
    );
}